# Website's icon url.
favicon: /favicon.png

# Open Graph metadata (https://hexo.io/docs/helpers.html#open-graph)
open_graph:
  twitter_id:
  twitter_site:
  google_plus:
  fb_admins:
  fb_app_id:

# Website's logo shown on the left of the navigation bar.
# It can either be an url to an image or a string if the following option is set.
# logo:
#   text: <logo string>
logo:
  text: A Developer's Blog

article:
  # Show word count and estimated reading time.
  readtime: true

# Navigation bar menu links.
menu:
  Archives: /archives
  #Lifestyle: /categories/LifeStyle
 # Music: /categories/Music
 # Technology: /categories/Technology
 # About: /about

# Search plugin settings.
search:
  type: insight

# Share plugin settings.
share:
  type: addthis
  install_url: //s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5b3ae122d776597f

# Comment plugin settings.
comment:
  type: disqus
  shortname: scottwestover

# Other plugins and their settings.
plugins:
  mathjax: true
  gallery: true
  google-analytics:
    tracking_id: UA-65933410-1

# Additional navigation bar links on the right.
# Links can either be text or icon. The following link is set to be an icon link whose icon
# is set to the class name of a FontAwesome 5 icon. The `footer_links` below also gives an
# example of setting plain text links.
navbar_links:
  GitHub:
    icon: fab fa-github
    url: https://github.com/scottwestover/scottwestover.github.io

# Links at the bottom of the page.
footer_links:
  GitHub: https://github.com/scottwestover/scottwestover.github.io
